"""Initial migration after refactor

Revision ID: bce0026412da
Revises: 
Create Date: 2026-01-10 15:35:41.692009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce0026412da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_item_markers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_markers_user_type'))
        batch_op.drop_constraint(batch_op.f('uq_user_item_marker'), type_='unique')
        batch_op.create_unique_constraint('_user_item_marker_uc', ['user_id', 'item_id', 'marker_type'])
        batch_op.create_index('ix_user_item_markers_user_type', ['user_id', 'marker_type'], unique=False)
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_item_markers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.TEXT(), nullable=True))
        batch_op.drop_index('ix_user_item_markers_user_type')
        batch_op.drop_constraint('_user_item_marker_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_item_marker'), ['user_id', 'item_id', 'marker_type'])
        batch_op.create_index(batch_op.f('ix_markers_user_type'), ['user_id', 'marker_type'], unique=False)

    # ### end Alembic commands ###
