"""Add UserKanjiHistory

Revision ID: 136cd32b3f64
Revises: f45a60d5d624
Create Date: 2026-03-08 12:29:55.198696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136cd32b3f64'
down_revision = 'f45a60d5d624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_kanji_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kanji', sa.String(length=1), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('first_searched_at', sa.DateTime(), nullable=False),
    sa.Column('last_searched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kanji', name='uq_user_kanji')
    )
    with op.batch_alter_table('user_kanji_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_kanji_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_kanji_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_kanji_history_user_id'))

    op.drop_table('user_kanji_history')
    # ### end Alembic commands ###
