"""add ai_contents table for versioning

Revision ID: 24c655513239
Revises: 67a39946737d
Create Date: 2026-02-06 23:32:40.295752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c655513239'
down_revision = '67a39946737d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_contents',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    with op.batch_alter_table('ai_contents', schema=None) as batch_op:
        batch_op.create_index('ix_ai_contents_content_type', ['content_type'], unique=False)
        batch_op.create_index('ix_ai_contents_item_id', ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_contents', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_contents_item_id')
        batch_op.drop_index('ix_ai_contents_content_type')

    op.drop_table('ai_contents')
    # ### end Alembic commands ###
