"""Add stop_requested to generation logs

Revision ID: 67a39946737d
Revises: 19611226b70b
Create Date: 2026-02-05 17:13:43.347070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a39946737d'
down_revision = '19611226b70b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_generator_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stop_requested', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_generator_logs', schema=None) as batch_op:
        batch_op.drop_column('stop_requested')

    # ### end Alembic commands ###
