"""add user_question to ai_contents

Revision ID: aa2eb00b128e
Revises: 24c655513239
Create Date: 2026-02-06 23:36:16.072216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2eb00b128e'
down_revision = '24c655513239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_question', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_contents', schema=None) as batch_op:
        batch_op.drop_column('user_question')

    # ### end Alembic commands ###
