"""Add central_auth_id to User

Revision ID: dc9d02a319dd
Revises: f2459aa4695b
Create Date: 2026-03-30 16:43:56.906888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9d02a319dd'
down_revision = 'f2459aa4695b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('central_auth_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_central_auth_id'), ['central_auth_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_central_auth_id'))
        batch_op.drop_column('central_auth_id')

    # ### end Alembic commands ###
