"""add study_planner tables

Revision ID: f2459aa4695b
Revises: 136cd32b3f64
Create Date: 2026-03-19 19:49:31.517829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2459aa4695b'
down_revision = '136cd32b3f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_end_date', sa.Date(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('initial_learned', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['learning_containers.container_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.create_index('ix_study_plan_user_container_status', ['user_id', 'container_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_plans_container_id'), ['container_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_plans_user_id'), ['user_id'], unique=False)

    op.create_table('study_plan_daily_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('target_new_cards', sa.Integer(), nullable=False),
    sa.Column('actual_new_cards', sa.Integer(), nullable=False),
    sa.Column('cumulative_learned', sa.Integer(), nullable=False),
    sa.Column('is_met', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id'),
    sa.UniqueConstraint('plan_id', 'date', name='uq_plan_date_log')
    )
    with op.batch_alter_table('study_plan_daily_logs', schema=None) as batch_op:
        batch_op.create_index('ix_daily_log_date', ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_plan_daily_logs_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plan_daily_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_plan_daily_logs_plan_id'))
        batch_op.drop_index('ix_daily_log_date')

    op.drop_table('study_plan_daily_logs')
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_plans_container_id'))
        batch_op.drop_index('ix_study_plan_user_container_status')

    op.drop_table('study_plans')
    # ### end Alembic commands ###
