"""remove ai_explanation column from learning_items

Revision ID: f45a60d5d624
Revises: aa2eb00b128e
Create Date: 2026-02-06 23:48:16.471669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45a60d5d624'
down_revision = 'aa2eb00b128e'
branch_labels = None
depends_on = None


def upgrade():
    # ### Data Migration: Copy existing ai_explanation to ai_contents ###
    conn = op.get_bind()
    conn.execute(sa.text("""
        INSERT INTO ai_contents (item_id, content_type, content_text, is_primary, created_at)
        SELECT item_id, 'explanation', ai_explanation, 1, CURRENT_TIMESTAMP
        FROM learning_items
        WHERE ai_explanation IS NOT NULL AND ai_explanation != ''
    """))
    # ### End Data Migration ###

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_items', schema=None) as batch_op:
        batch_op.drop_column('ai_explanation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_explanation', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
