"""Add translation history

Revision ID: fa7e7651284c
Revises: 
Create Date: 2026-01-15 20:03:52.467172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7e7651284c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.create_index('ix_review_logs_container', ['container_id'], unique=False)
        batch_op.create_index('ix_review_logs_session', ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_review_logs_session')
        batch_op.drop_index('ix_review_logs_container')

    # ### end Alembic commands ###
